sudo: required
services:
  - docker

language: python

branches:
  - development
  - master
  - /.*release.*/

python:
  - "3.6"


before_script:
  - docker build -t pdf2identity .
  - docker run -d -p 8000:8000 --name pdf2identity pdf2identity


script:
  - docker exec pdf2identity coverage erase
  - docker exec pdf2identity coverage run --source='.' manage.py test
  - docker exec pdf2identity coverage report
  - docker exec pdf2identity flake8

after_script:
  - docker stop pdf2identity

after_success:
  - coveralls

deploy:
  - provider: script
    script: bash scripts/deploy.sh
    on:
      branch: development
  - provider: script
    script: bash scripts/sendZip.sh
    on:
      branch: master

addons:
  apt:
    packages:
      - docker-ce
